name: cnf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - pip
  - pip:
    - normflows
    - pickle5